name: Sync to Hugging Face Hub

on:
push:
branches:
- main
workflow_dispatch:

jobs:
sync:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repo
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
      lfs: true

  - name: Push to Hugging Face
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    run: |
      git push --force https://pavandoddavarapu:$HF_TOKEN@huggingface.co/spaces/pavandoddavarapu/anpr_atcc_project main